name: CentOS 8 RDP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up CentOS 8
        run: |
          sudo docker run -d --name centos8-vps --privileged centos:8 sleep infinity
          sleep 10
          sudo docker exec centos8-vps bash -c "
            dnf install -y epel-release
            dnf install -y xrdp
            systemctl enable xrdp
            systemctl start xrdp
          "

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok-v3-stable-linux-amd64.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create RDP User
        run: |
          sudo docker exec centos8-vps bash -c "
            useradd -m -s /bin/bash rdpuser
            echo 'rdpuser:Datnguyentv.com' | chpasswd
          "

      - name: Start Ngrok Tunnel
        run: ngrok tcp 3389
