name: CentOS 8 RDP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: centos-latest

    steps:
      - name: Set up CentOS 8
        run: |
          sudo docker run -d --name centos8-vps --privileged -it centos:8 /sbin/init
          sleep 10
          sudo docker exec -it centos8-vps bash -c "
            yum install -y epel-release
            yum install -y xrdp
            systemctl enable xrdp
            systemctl start xrdp
          "

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok-v3-stable-linux-amd64.zip
          chmod +x ngrok
          mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create RDP User
        run: |
          sudo docker exec -it centos8-vps bash -c "
            useradd -m -s /bin/bash rdpuser
            echo 'rdpuser:Datnguyentv.com' | chpasswd
          "

      - name: Start Ngrok Tunnel
        run: ngrok tcp 3389
